dist: trusty
language: r
r: bioc-release

cache: packages

warnings_are_errors: false

sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

notifications:
    slack: pathogens:8NUkMUXlMNecj9NXnwTKbBQU
